### ISSUE TITLE
Offline Setup Instructions

### ISSUE THREAD

**Issue by richplastow** [aidsalliance/cell-survivor#5]
It would be useful to be able to play the game without Internet access, as some countries have real connectivity issues. The GitHub wiki should contain instructions on setting up the game locally on a PC or Mac (using the ‘development environment’). Obviously an Internet connection will be needed for the initial setup, but afterwards the the game will be playable any time, without further internet connection.

**Comment by KatiByrne** [comment]
internet connectivity is a bit of an issue for some developing countries. being able to play the game offline would be useful indeed... would you get a prompt at the end to upload your scores online if you score really high ;o)

**Comment by richplastow** [comment]
The highscore-upload system still works in offline mode … you would need Internet connection to upload the score, but it’s not much data so it should work on a slow connection.
